; ##################################################################################
; # This #Include file was generated by Image2Include.ahk, you must not change it! #
; ##################################################################################
Create_unmute_png(NewHandle := False) {
Static hBitmap := 0
If (NewHandle)
   hBitmap := 0
If (hBitmap)
   Return hBitmap
VarSetCapacity(B64, 1204 << !!A_IsUnicode)
B64 := "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAAK/INwWK6QAAABl0RVh0U29mdHdhcmUAQWRvYmUgSW1hZ2VSZWFkeXHJZTwAAAMZSURBVHjaYlRS0mB4+vQJg6ioBAM/vxDDmzcvGTg5uRhYWdkZBASEgGJ8bMLCopNERESS37x5t/7nzx+J69cv+MoABQABxMSAAzAyMjL8/v2bhYuLq0lOTi7d0FCHRUVFIRQo5oOsDiCAcBrw69cvoAsE0ry83IvFxYUY2NhYGDQ1VRjY2dn8kNUBBBBWA/7+/cvAwsLqERsb1aWiIs/y69cnoBf5GcTERICG8ukiqwUIIAwD/v37BzTgn250dMS02NhQ7tu3bzH8/PkdGC4cQM28DHx8PPzI6gECCMWA////MXz79l3Y3d1tbl5etuKHD58ZHjy4x8DExATEzAwcHJwM3NxAk5AAQACx/P//H+jfn0CN3xRZWTlMgJrTKipKTN+9+87w/ft7hg8fvjG8fv0e6LI/QP+zAw3gQrEUIIBYBAQE20JCwt3V1DTF5OQURExMjDhev/4G1PiaQVKSj8Ha2onh8eM7DPfv32dQUFBmYGZmRjEAIIBYqqoqM93dPQRevHgHtPEnw8WLNxlATpeVFQdG4x+g2G+g//mBYh+BUfsf6JK//5ENAAggli9fvv0+ceIKw61b90GmMwD5oFQANkRYmJvh/ftPDPfu3WfQ05MEGsAElP/8F9kAgABiOX3i1If/ZgKiDx48AwYSKzAFMgMDkwmckKSlQSnzGcPLlw+AzrcAhtVvhrdv3/5CNgAggJjOXjh96cfPr8B4ZwQG5BeGz58+MPz6+YPh06evDB8/fgMa9olBXV0a6BoRhs+fPzO8evXyI7IBAAHEcv786WmfPrUoMTAwASPk7+f/f/8wy8mpGalpGHN9/CgBDAsFoLPfAv3OALT9PTBAH99GNgAggICp7Oe+69cvGIE46up6DO8+vGW4dXdD4M3blxt//AjQtbW1BHrnN8OfP78Zbt68xXD37u3DyAYABBA8SkCJBUwDA4qdjXP9o0d3vJYunTZh//49/9jZQWHxhWH37t1v3r17sw/ZAIAAYkA2AOQCcTEpYGByAWOEBSzOw8Pr7eTkdS86Ovk3H59APgPErwwwDBBgALmJNPlcAbP7AAAAAElFTkSuQmCC"
If !DllCall("Crypt32.dll\CryptStringToBinary", "Ptr", &B64, "UInt", 0, "UInt", 0x01, "Ptr", 0, "UIntP", DecLen, "Ptr", 0, "Ptr", 0)
   Return False
VarSetCapacity(Dec, DecLen, 0)
If !DllCall("Crypt32.dll\CryptStringToBinary", "Ptr", &B64, "UInt", 0, "UInt", 0x01, "Ptr", &Dec, "UIntP", DecLen, "Ptr", 0, "Ptr", 0)
   Return False
; Bitmap creation adopted from "How to convert Image data (JPEG/PNG/GIF) to hBITMAP?" by SKAN
; -> http://www.autohotkey.com/board/topic/21213-how-to-convert-image-data-jpegpnggif-to-hbitmap/?p=139257
hData := DllCall("Kernel32.dll\GlobalAlloc", "UInt", 2, "UPtr", DecLen, "UPtr")
pData := DllCall("Kernel32.dll\GlobalLock", "Ptr", hData, "UPtr")
DllCall("Kernel32.dll\RtlMoveMemory", "Ptr", pData, "Ptr", &Dec, "UPtr", DecLen)
DllCall("Kernel32.dll\GlobalUnlock", "Ptr", hData)
DllCall("Ole32.dll\CreateStreamOnHGlobal", "Ptr", hData, "Int", True, "PtrP", pStream)
hGdip := DllCall("Kernel32.dll\LoadLibrary", "Str", "Gdiplus.dll", "UPtr")
VarSetCapacity(SI, 16, 0), NumPut(1, SI, 0, "UChar")
DllCall("Gdiplus.dll\GdiplusStartup", "PtrP", pToken, "Ptr", &SI, "Ptr", 0)
DllCall("Gdiplus.dll\GdipCreateBitmapFromStream",  "Ptr", pStream, "PtrP", pBitmap)
DllCall("Gdiplus.dll\GdipCreateHBITMAPFromBitmap", "Ptr", pBitmap, "PtrP", hBitmap, "UInt", 0)
DllCall("Gdiplus.dll\GdipDisposeImage", "Ptr", pBitmap)
DllCall("Gdiplus.dll\GdiplusShutdown", "Ptr", pToken)
DllCall("Kernel32.dll\FreeLibrary", "Ptr", hGdip)
DllCall(NumGet(NumGet(pStream + 0, 0, "UPtr") + (A_PtrSize * 2), 0, "UPtr"), "Ptr", pStream)
Return hBitmap
}