; ##################################################################################
; # This #Include file was generated by Image2Include.ahk, you must not change it! #
; ##################################################################################
Create_add_png(NewHandle := False) {
Static hBitmap := 0
If (NewHandle)
   hBitmap := 0
If (hBitmap)
   Return hBitmap
VarSetCapacity(B64, 1100 << !!A_IsUnicode)
B64 := "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAEnQAABJ0BfDRroQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAAKdEVYdFRpdGxlAFBsdXOb2MyuAAAAE3RFWHRBdXRob3IARmxvcmlhbiBIYWFny2nXdQAAABh0RVh0Q3JlYXRpb24gVGltZQAyMDEwLTAyLTAz9BddIQAAAltJREFUOI2Nk81LVGEUxp/z3jszzh01/EjJIojGEIQW1jpo1SYQalFEq6Jt/0MURBAVtK59i7Bs0wdEURBkhU5FYjCRi0RMzRnvve/nOS20NJugszmb3znPA+c5JCJoVRdqJ8+JUduYGemKfnntyP0JEQlbubjVMBGpO3NXLu3tGe6zbDD+9O694eHhs0S0LFsUVasF1Wq1kOksSn0TqWtgcbaxP4qigVZsSwfeezIup8w1YIOByU07M7dtVW/pgIioUqlw7nKkronUN+HZhWKxaIko+os/8+yg6ir0j9rUl733FMRzyFHcNzh4fUf/zi4bNJ6MP/+Rr+Y3igN+1odAzCK6YWuPz3+ZotHbQz1HDx+r93b0dVo2cMHABg0mhmMDywa5S2GchmMNFywsa3x+/e3RzFU5Hbu5YtE4rRwMnBhY0bAwsF6vLQgaNhhYaFjZ6Pl8GEqS9l1x8AEr2ZKKS2pNnQ1c0BAlcGJhg0ZmNxzYYNe6sR3e+yTO3iSNV/HkxdU6HxdGWUTAgYtDp7r29O7uiC0bTI59dc0PUV2IHbMUIGButL0DsBy/eDCRVT9Vb0VRNFYulzuJSJh8wUr6MPXotEHDZdI0M22XmfkjMwelVATAKqVm4/XbLhDR91+nOXTiQKI5dbELcMEgwBql1FStVnsvIoGICACJCP/OgWwqLmmlbUaZayL1DTjvSUQIAG9i+Z9JTCqJyuw8sRW4YOBcidZt/1+UdT22KyV/EwvJKKRUwWLythDHSwAIwB9xpn+988jIyPYQQreIdDNz5r2vT09PN7dyPwHYQK0SgUc5EAAAAABJRU5ErkJggg=="
If !DllCall("Crypt32.dll\CryptStringToBinary", "Ptr", &B64, "UInt", 0, "UInt", 0x01, "Ptr", 0, "UIntP", DecLen, "Ptr", 0, "Ptr", 0)
   Return False
VarSetCapacity(Dec, DecLen, 0)
If !DllCall("Crypt32.dll\CryptStringToBinary", "Ptr", &B64, "UInt", 0, "UInt", 0x01, "Ptr", &Dec, "UIntP", DecLen, "Ptr", 0, "Ptr", 0)
   Return False
; Bitmap creation adopted from "How to convert Image data (JPEG/PNG/GIF) to hBITMAP?" by SKAN
; -> http://www.autohotkey.com/board/topic/21213-how-to-convert-image-data-jpegpnggif-to-hbitmap/?p=139257
hData := DllCall("Kernel32.dll\GlobalAlloc", "UInt", 2, "UPtr", DecLen, "UPtr")
pData := DllCall("Kernel32.dll\GlobalLock", "Ptr", hData, "UPtr")
DllCall("Kernel32.dll\RtlMoveMemory", "Ptr", pData, "Ptr", &Dec, "UPtr", DecLen)
DllCall("Kernel32.dll\GlobalUnlock", "Ptr", hData)
DllCall("Ole32.dll\CreateStreamOnHGlobal", "Ptr", hData, "Int", True, "PtrP", pStream)
hGdip := DllCall("Kernel32.dll\LoadLibrary", "Str", "Gdiplus.dll", "UPtr")
VarSetCapacity(SI, 16, 0), NumPut(1, SI, 0, "UChar")
DllCall("Gdiplus.dll\GdiplusStartup", "PtrP", pToken, "Ptr", &SI, "Ptr", 0)
DllCall("Gdiplus.dll\GdipCreateBitmapFromStream",  "Ptr", pStream, "PtrP", pBitmap)
DllCall("Gdiplus.dll\GdipCreateHBITMAPFromBitmap", "Ptr", pBitmap, "PtrP", hBitmap, "UInt", 0)
DllCall("Gdiplus.dll\GdipDisposeImage", "Ptr", pBitmap)
DllCall("Gdiplus.dll\GdiplusShutdown", "Ptr", pToken)
DllCall("Kernel32.dll\FreeLibrary", "Ptr", hGdip)
DllCall(NumGet(NumGet(pStream + 0, 0, "UPtr") + (A_PtrSize * 2), 0, "UPtr"), "Ptr", pStream)
Return hBitmap
}